export const initialState = {
  posts: [
    {
      id: 1,
      title: 'Amethyst',
      text: 'Amethyst is a violet variety of quartz. The ancient Greeks wore amethyst and carved drinking vessels from it in the belief that it would prevent intoxication. Amethyst is a semiprecious stone that is often used in jewelry and is the traditional birthstone for February.',
      price: '100 $',
      price2: '180 $',
      price3: '150 $',
      photoDescription: 'Amethyst sample photos',
      photoDescription2: 'Choose type of amethyst jewelry you want to order',
      photo: '/images/mineral-1-photo-1.jpg',
      photo2: '/images/mineral-1-photo-2.jpg',
      photo3: '/images/mineral-1-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
    {
      id: 2,
      title: 'Fluorite',
      text: 'Fluorite (also called fluorspar) is the mineral form of calcium fluoride. Pure fluorite is transparent, both in visible and ultraviolet light, but impurities usually make it a colorful mineral and the stone has ornamental and lapidary uses.',
      price: '120 $',
      price2: '170 $',
      price3: '145 $',
      photoDescription: 'Fluorite sample photos',
      photoDescription2: 'Choose type of fluorite jewelry you want to order',
      photo: '/images/mineral-2-photo-1.jpg',
      photo2: '/images/mineral-2-photo-2.jpg',
      photo3: '/images/mineral-2-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
    {
      id: 3,
      title: 'Marcasite',
      text: ' It is physically and crystallographically distinct from pyrite, which is iron sulfide with cubic crystal structure. On fresh surfaces it is pale yellow to almost white and has a bright metallic luster. It tarnishes to a yellowish or brownish color and gives a black streak.',
      price: '110 $',
      price2: '160 $',
      price3: '95 $',
      photoDescription: 'Marcasite sample photos',
      photoDescription2: 'Choose type of marcasite jewelry you want to order',
      photo: '/images/mineral-3-photo-1.jpg',
      photo2: '/images/mineral-3-photo-2.jpg',
      photo3: '/images/mineral-3-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
    {
      id: 4,
      title: 'Ammonite',
      text: 'The name ammonite, from which the scientific term is derived, was inspired by the spiral shape of their fossilized shells, which somewhat resemble tightly coiled horns. Pliny the Elder (d. 79 AD near Pompeii) called fossils of these animals ammonis cornua (horns of Ammon) because the Egyptian god Ammon (Amun) was typically depicted wearing horns',
      price: '130 $',
      price2: '200 $',
      price3: '170 $',
      photoDescription: 'Ammonite sample photos',
      photoDescription2: 'Choose type of ammonite jewelry you want to order',
      photo: '/images/mineral-4-photo-1.jpg',
      photo2: '/images/mineral-4-photo-2.jpg',
      photo3: '/images/mineral-4-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
    {
      id: 5,
      title: 'Apatite',
      text: 'Major sources for this gem are Brazil, Myanmar, and Mexico. Other sources include Canada, Czech Republic, Germany, India, Madagascar. Moon rocks collected by astronauts during the Apollo program contain traces of apatite.',
      price: '115 $',
      price2: '195 $',
      price3: '145 $',
      photoDescription: 'Apatite sample photos',
      photoDescription2: 'Choose type of apatite jewelry you want to order',
      photo: '/images/mineral-5-photo-1.jpg',
      photo2: '/images/mineral-5-photo-2.jpg',
      photo3: '/images/mineral-5-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
    {
      id: 6,
      title: 'Agate',
      text: 'It consists of chalcedony and quartz as its primary components. Agates are primarily formed within volcanic and metamorphic rocks. The ornamental use of agate dates back to Ancient Greece in assorted jewelry and in the seal stones of Greek warriors.',
      price: '125 $',
      price2: '210 $',
      price3: '170 $',
      photoDescription: 'Agate sample photos',
      photoDescription2: 'Choose type of agate jewelry you want to order',
      photo: '/images/mineral-6-photo-1.jpg',
      photo2: '/images/mineral-6-photo-2.jpg',
      photo3: '/images/mineral-6-photo-3.jpg',
      photoBracelet: '/images/bracelet-black-and-white.jpg',
      photoEarings: '/images/earings-black-and-white.jpg',
      photoRing: '/images/ring-black-and-white.jpg',
      quantity: '1',
    },
  ],
};
